/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.Logic;

import client.Acquaintance.IAdmin;
import client.Acquaintance.ICustomer;
import client.Acquaintance.ILink;
import client.Acquaintance.ILogic;

/**
 *
 * @author Jeppe Enevold
 */
public class LogicFacade implements ILogic {

    private static ILink link;
    private ICustomer customer;
    private IAdmin admin;
    private MessageParser messageParser = new MessageParser(this);
    private LogoutTimer timer = new LogoutTimer();

    @Override
    public void injectLink(ILink LinkLayer) {
        link = LinkLayer;
    }

    @Override
    public void startConnection() {
        link.startConnection();
    }
    @Override
    public void updateTimer(){
        timer.updateTimer();
    }

    @Override
    public void sendMessage(String message) {
        link.sendMessage(message);
    }

    @Override
    public String receiveMessage() {
        return link.receiveMessage();
    }

    @Override
    public String login(String ID, String password) {
        this.timer = new LogoutTimer();
        sendMessage(messageParser.toProtocol00(ID, password));
        String message = receiveMessage();

        if (message.equalsIgnoreCase("true")) {
            initializeUser(ID);
        }

        return message;
    }

    @Override
    public String logout() {
       //this.timer.cancel();
        String message = "";
        if(customer != null && admin == null){
            message = messageParser.toProtocol18(customer.getID());
        }else if(admin != null && customer == null){
            message = messageParser.toProtocol18(admin.getID());
        }else{
            System.out.println("logout error - customer and admin is either both null or not null");
        }

        sendMessage(message);
        String receivedMessage = receiveMessage();

        if (receivedMessage.equalsIgnoreCase("true")) {
            admin = null;
            customer = null;
            link.endConnection();
            link.startConnection(); //the connection is started again to make it possible to log in again
            return "true";
        } else {
            return "false";
        }
    }

    @Override
    public int getAccountBalance(String accountID) {
        sendMessage(messageParser.toProtocol02(accountID, customer.getID()));
        return Integer.parseInt(receiveMessage());
    }
    
    @Override
    public long getimeRemaining() {
        long timeRemaining = timer.getimeRemaining();
        return timeRemaining;
    }
    public void initializeUser(String ID) {
        if (ID.startsWith("A")) {
            admin = new Admin(ID, this);

        } else if (ID.startsWith("C")) {
            customer = new Customer(ID, this);
        }
    }

    @Override
    public String toProtocol05(String senderID, String amount, String recieverID, String text) {
        sendMessage(messageParser.toProtocol05(senderID, amount, recieverID, text, customer.getID()));
        return receiveMessage();
    }

    @Override
    //This method could also be renamed to an appropriate name since the arcitecture has changed. For instance createCustomer(). This is preffered.
    public String toProtocol07(String ID, String name, String birthday, String phonenumber, String address, String email, String password) {
        sendMessage(messageParser.toProtocol07(ID, name, birthday, phonenumber, address, email, password, admin.getID()));
        return receiveMessage();
    }

    @Override
    //This method will store the information for a specific customer
    public String toProtocol03(String name, String phoneNo, String address, String email) {
        sendMessage(messageParser.toProtocol03(name, phoneNo, address, email, customer.getID()));
        return receiveMessage();
    }

    @Override
    public ICustomer getCustomer() {
        return customer;
    }

    @Override
    public String getTransactionHistory(String accountID) {
        sendMessage(messageParser.toProtocol06(accountID, customer.getID()));
        return receiveMessage();
    }

    @Override
    public IAdmin getAdmin() {
        return admin;
    }

    @Override
    public String sendMailAutogenerated(String ID, String email, String name, String password) {
        sendMessage(messageParser.toProtocol14(ID, email, name, password));
        return receiveMessage();
    }

    @Override
    public String toProtocol09(String ID, boolean open) {
        sendMessage(messageParser.toProtocol09(ID, open, admin.getID()));
        return receiveMessage();
    }

    @Override
    public String updatePassword(String ID, String oldPassword, String newPassword) {
        sendMessage(messageParser.toProtocol13(ID, oldPassword, newPassword));
        return receiveMessage();
    }

    @Override
    public String checkPassword(String ID, String password) {
        sendMessage(messageParser.toProtocol16(ID, password));
        return receiveMessage();
    }

    public String contactBank(String ID, String subject, String text) {
        sendMessage(messageParser.toProtocol15(ID, subject, text, customer.getEmail()));
        return receiveMessage();
    }

    @Override
    public String openBankAccount() {
        String ID = customer.getID();
        sendMessage(messageParser.toProtocol12(ID, customer.getID()));
        return receiveMessage();
    }

    @Override
    public String lastLogin() {
        sendMessage(messageParser.toProtocol04(customer.getID()));
        return receiveMessage();
    }

    @Override
    public void cancelTimer() {
        timer.cancelTimer();
    }
    
    
    
}
